apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    env: production
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: sample-container
        image: nginx
        ports:
        - containerPort: 80
